alter table user_stocks
    add investment_type_id bigint not null
        references investment_types;

alter table user_stocks_movements
    add investment_type_id bigint not null
        references investment_types;

-- 2022-08-30
alter table user_stocks
    add buy_date timestamp;

alter table user_stocks
    add sell_date timestamp;

alter table user_stocks
    add end_date timestamp;


alter table stocks
    add ev_ebit numeric;

-- 2022-09-01
create table stocks_prices
(
    id            bigint generated by default as identity
        primary key,
    investment_id bigint  not null
        constraint user_stocks_stocks_id_fk
            references stocks,
    price         numeric not null,
    date_value    timestamp default now(),
    last_update   timestamp default now()
);

alter table stocks
    add prices_imported text default 'N';

create index index_select_price
    on stocks_prices (date_value desc, investment_id desc);

-- 2022-09-02
create table http_schedule
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(50) not null,
    every       text        not null,
    period      text        not null,
    method      text        not null,
    url         text        not null,
    body        text,
    is_active   text        not null default 'S',
    last_update timestamp   not null default current_timestamp
);

--2022-09-23
alter table stocks
    add tx_type text;

alter table stocks
    add tx_quotient numeric;

alter table stocks
    alter column url_infos drop not null;

alter table user_stocks_movements
    add buy_date timestamp;


create table taxs
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(50) not null,
    value       numeric     not null,
    date_value  timestamp default now(),
    last_update timestamp default now()
);

INSERT INTO public.taxs (name, value, date_value, last_update)
VALUES ('CDI', 13.65, '2022-08-04 00:00:00.000000', DEFAULT);
INSERT INTO public.taxs (name, value, date_value, last_update)
VALUES ('CDI', 13.15, '2022-06-17 00:00:00.000000', DEFAULT);
INSERT INTO public.taxs (name, value, date_value, last_update)
VALUES ('CDI', 12.75, '2022-05-05 00:00:00.000000', DEFAULT);
INSERT INTO public.taxs (name, value, date_value, last_update)
VALUES ('CDI', 11.75, '2022-03-17 00:00:00.000000', DEFAULT);
INSERT INTO public.taxs (name, value, date_value, last_update)
VALUES ('CDI', 10.75, '2022-02-03 00:00:00.000000', DEFAULT);
INSERT INTO public.taxs (name, value, date_value, last_update)
VALUES ('CDI', 9.25, '2021-12-09 00:00:00.000000', DEFAULT);

-- 2022-10-18
create table external_dash
(
    id          bigint generated by default as identity
        primary key,
    hash        text not null,
    client_name text not null
);

-- 2022-10-30
create table dividend_types
(
    id       serial       not null
        constraint dividend_types_pkey
            primary key,
    name     varchar(255) not null,
    rend_tax numeric      not null
);
create table dividends
(
    id              serial primary key,
    investment_id   int       not null,
    date_payment    date      not null default now(),
    quantity        numeric   not null,
    value_per_quote numeric   not null,
    user_id         bigint    not null
        constraint user_stocks_user_id_fk
            references users,
    type_id         int       not null
        constraint dividend_types_id_fk references dividend_types (id),
    last_update     timestamp not null default now()
);


-- 2022-11-01


create table profit_loss
(
    id            serial primary key,
    investment_id int       not null,
    date_sell     date      not null default now(),
    quantity      numeric   not null,
    value         numeric   not null,
    user_id       bigint    not null
        constraint user_stocks_user_id_fk
            references users,
    last_update   timestamp not null default now()
);

-- 2022-11-07
create table transactions
(
    id           serial primary key,
    date         date      not null default now(),
    type         text      null,
    value        numeric   not null,
    name         text      null,
    package_name text      null,
    app_name     text      null,
    text         text      null,
    user_id      bigint    not null
        constraint user_stocks_user_id_fk
            references users,
    last_update  timestamp not null default now()
);