alter table user_stocks
    add investment_type_id bigint not null
        references investment_types;

alter table user_stocks_movements
    add investment_type_id bigint not null
        references investment_types;

-- 2022-08-30
alter table user_stocks
    add buy_date timestamp;

alter table user_stocks
    add sell_date timestamp;

alter table user_stocks
    add end_date timestamp;


alter table stocks
    add ev_ebit numeric;

-- 2022-09-01
create table stocks_prices
(
    id            bigint generated by default as identity
        primary key,
    investment_id bigint  not null
        constraint user_stocks_stocks_id_fk
            references stocks,
    price     numeric not null,
    date_value timestamp default now(),
    last_update   timestamp default now()
);

alter table stocks
    add prices_imported text default 'N';

create index index_select_price
    on stocks_prices (date_value desc, investment_id desc);