create table investment_types
(
    id      bigint generated by default as identity
        primary key,
    ticker  text    not null,
    name    text    not null,
    enabled boolean not null default true
);

create table user_stocks
(

    id          bigint generated by default as identity
        primary key,
    investment_id     bigint  not null
        constraint user_stocks_investment_type_id_fk
            references investment_types,
    avg_price   numeric not null,
    quantity    numeric not null,
    user_id     bigint  not null
        constraint user_stocks_user_id_fk
            references users,
    last_update timestamp default now()
);

create table movement_types
(
    id          bigint generated by default as identity
        primary key,
    name        text    not null,
    coefficient numeric not null default 1,
    enabled     boolean not null default true
);

create table user_stocks_movements
(
    id            bigint generated by default as identity
        primary key,
    investment_id     bigint  not null
        constraint user_stocks_movements_investment_type_id_fk
            references investment_types,
    quantity      numeric not null,
    price         numeric not null,
    user_id       bigint  not null
        constraint user_stocks_user_id_fk
            references users,
    date          timestamp default now(),
    movement_type bigint  not null
        constraint user_stocks_movements_movement_type_id_fk
            references movement_types
);

create table fiis
(
    companyname          text,
    ticker               text,
    price                numeric,
    gestao               text,
    dy                   numeric,
    p_vp                 numeric,
    valorpatrimonialcota numeric,
    liquidezmediadiaria  numeric,
    percentualcaixa      numeric,
    dividend_cagr        numeric,
    numerocotistas       numeric,
    numerocotas          numeric,
    patrimonio           numeric,
    lastdividend         numeric,
    desv_dy              numeric,
    rank_dy              numeric,
    rank_pvp             numeric,
    rank_desv_dy         numeric,
    segment              text,
    last_update          timestamp default now()
);

alter table fiis
    owner to postgres;

