create table movement_types
(
    id          bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    name        text                 not null,
    coefficient numeric default 1    not null,
    enabled     boolean default true not null,
    to_balance  boolean default false
);

alter table movement_types
    owner to postgres;

create table investment_types
(
    id      bigint generated by default as identity
        primary key,
    name    text                 not null,
    enabled boolean default true not null
);

alter table investment_types
    owner to postgres;

create table stocks
(
    id                 bigint generated by default as identity
        primary key,
    ticker             text                   not null,
    name               text                   not null,
    investment_type_id bigint                 not null
        references investment_types,
    url_infos          text                   not null,
    enabled            boolean   default true not null,
    last_update        timestamp default now(),
    desv_dy            numeric,
    price              numeric,
    segment            text,
    dy                 numeric,
    pvp                numeric,
    pl                 numeric,
    avg_liquidity      numeric,
    last_dividend      numeric,
    rank_dy            numeric,
    rank_pvp           numeric,
    rank_desv_dy       numeric,
    rank_pl            numeric
);

alter table stocks
    owner to postgres;

create table user_stocks
(
    id            bigint generated by default as identity
        primary key,
    investment_id bigint  not null
        constraint user_stocks_stocks_id_fk
            references stocks,
    avg_price     numeric not null,
    quantity      numeric not null,
    user_id       bigint  not null
        constraint user_stocks_user_id_fk
            references users,
    last_update   timestamp default now()
);

alter table user_stocks
    owner to postgres;

create table user_stocks_movements
(
    id            bigint generated by default as identity
        primary key,
    investment_id bigint  not null
        constraint user_stocks_movements_stocks_id_fk
            references stocks,
    quantity      numeric not null,
    price         numeric not null,
    user_id       bigint  not null
        constraint user_stocks_user_id_fk
            references users,
    date          timestamp default now(),
    movement_type bigint  not null
        constraint user_stocks_movements_movement_type_id_fk
            references movement_types
);

alter table user_stocks_movements
    owner to postgres;

