

create table user_stocks
(

    id        bigint generated by default as identity
        primary key,
    ticker    text    not null,
    avg_price numeric not null,
    quantity  numeric not null,
    user_id   bigint  not null
        constraint user_stocks_user_id_fk
            references users,
    last_update          timestamp default now()
);

create table fiis
(
    companyname          text,
    ticker               text,
    price                numeric,
    gestao               text,
    dy                   numeric,
    p_vp                 numeric,
    valorpatrimonialcota numeric,
    liquidezmediadiaria  numeric,
    percentualcaixa      numeric,
    dividend_cagr        numeric,
    numerocotistas       numeric,
    numerocotas          numeric,
    patrimonio           numeric,
    lastdividend         numeric,
    desv_dy              numeric,
    rank_dy              numeric,
    rank_pvp             numeric,
    rank_desv_dy         numeric,
    segment              text,
    last_update          timestamp default now()
);

alter table fiis
    owner to postgres;

